import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
          <div className="flex min-h-screen w-full">
            {/* sidebar left */}
            {/* <AppSidebar /> */}
            

            <main className="flex flex-col items-center justify-center min-h-screen w-full">
              <header className="lg:hidden absolute top-4 left-4 bg-slate-500">
               
              </header>
              <div className="flex flex-col justify-center w-full mx-auto">
                {children}
              </div>
            </main>
          </div>
        
      </body>
    </html>
  );
}
